### ISSUE TITLE
`Unexpected Error` while trying to create a shortlink with query parameters

### ISSUE THREAD

**Issue by oleggtro** [zekroTJA/vctr#15]
I think the title says it all. I checked the logs of the docker containers and the API response but I can't additional info for that error...
Is this just not supported, or are you planning on implementing it? The same error also occures random while creating shortlinks for seeminly no reason. Is there anything I can do to get a more detailed error msg?

**Comment by michihupf** [comment]
It also happens when editing a valid shortlink and adding query parameters to the redirect url. I opened up DevTools on the web app and found that there is a POST error: 400 Bad Request. It happens in main.js in line 190. It is obfuscated but I'm gonna investigate this issue further.

Edit: Line 190 in main.js:
```
window.fetch("/api/links/<uid>"), {
    method: POST,
    headers: {content-type: "application/json"},
    body: {"ident":"JQGMjU","destination":"https://google.de/search?q=test","creator":{"username":" 
       <username>","permissions":30,"last_login":"2021-02-12T08:39:47.63098","guid":"4c2dc85b-b380-4fca-bf5f- 
       341fa7c7f709","created":"2021-02- 
       12T08:38:42.337415"},"enabled":true,"permanent_redirect":true,"password_required":false,"last_access":"2021-02- 
       12T08:42:43.598205","access_count":2,"unique_access_count":2,"total_access_limit":0,"expires":"0001-01- 
       01T00:00:00","guid":"8691d656-5b1e-4f52-b68d-e8a4dbe847a3","created":"2021-02-12T08:41:12.809563"},
    credentials: "include"
});
```
This is what causes the "Unexpected Error" to be thrown on the web app. It is just a bad request to the backend. There are likely some issues in the API code.

**Comment by zekroTJA** [comment]
I've found some time to look into it:

The problem is the URL Regex, which checks the destination URL. For some reason, it rejects URL queries. To be honest, I've copied this regex on some web page when I was googling for good URL regex strings.

![image](https://user-images.githubusercontent.com/16734205/107756572-b18d2680-6d24-11eb-918f-fdcd24a0022f.png)
This is the current destination validation regex:
```regex
^(ht|f)tp(s?)\:\/\/[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&%\$#_]*)?$
```

**Comment by michihupf** [comment]
So I just found the folliwing code in `LinkUtil.cs`:

```csharp
public static async Task<bool> ValidateDestination(string destination)
        {
            if (!UrlRegex.IsMatch(destination))
                return false;
            using (var client = new HttpClient())
            {
                client.Timeout = TimeSpan.FromSeconds(10);

                try
                {
                    var res = await client.GetAsync(destination, HttpCompletionOption.ResponseHeadersRead);
                    return (int) res.StatusCode < 400;
                }
                catch
                {
                    return false;
                }
            }
        }
```

So I checked the RegEx and found out, that it doesn't fully cover URL support. When i use query parameters it cannot match because `=` is not allowed. This is crucial for URL Query Parameters though.

_Sidenote: https://google and https://google..de are valid URLs according to your RegEx (not that fixing it would matter as it would timeout anyways but could make the code more efficient in the future). Was that intended if yes why?_

Your RegEx: 
```
^(ht|f)tp(s?)\:\/\/[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&%\$#_]*)?$
```

My updated version to fix the issues above:
```
^(ht|f)tps?:\/\/(\w*\.)?\w+(\.\w{1,24})(:\d*)?([-\w()@:%_#\/]*)(\?[-\w()@:%_\+~#\/=&]*)?$
```

I tested it on https://regex101.com and it seemed to be working fine.
Just update it in `Constants.cs` and this error shouldn't be happening anymore

**Comment by michihupf** [comment]
> I've found some time to look into it:
> 
> The problem is the URL Regex, which checks the destination URL. For some reason, it rejects URL queries. To be honest, I've copied this regex on some web page when I was googling for good URL regex strings.
> 
> ![image](https://user-images.githubusercontent.com/16734205/107756572-b18d2680-6d24-11eb-918f-fdcd24a0022f.png)
> This is the current destination validation regex:
> 
> ```regexp
> ^(ht|f)tp(s?)\:\/\/[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&%\$#_]*)?$
> ```

oh didn't spot it haha. Yeah that was what i found as well. Copying regex is not good practice :D
But this bug should be solved then. 
Note the regex that I provided doesn't work for advanced URL syntax like: https://username:password@domain.tld

Edit: It also validates FTP URIs but I don't know if that is intended or not - that's why i kept it in
